export const ALL_TAGS = [
  "Level up",
  "Dungeons",
  "Monster battles",
  "Tower climbing",
  "Tests",
  "Betrayal",
  "Tournament",
  "Gods",
  "Friendship",
  "Vampires",
  "Nobility",
  "Training",
  "Secret organizations",
  "Revenge",
  "Monsters",
  "Survival",
  "Humanity",
  "Apocalypse",
  "Novel world",
  "Survival game",
  "Serial killers",
  "Family",
  "Trauma",
  "Appearance",
  "Bullying",
  "Social hierarchy",
  "Reincarnation",
  "Magic",
  "Coming of age",
  "Secret powers",
  "Cats",
  "Virtual reality",
  "Time travel",
  "Demons",
  "Angels",
  "Academy",
  "Adventure",
  "Alchemy",
  "Aliens",
  "Alternate dimension",
  "Amnesia",
  "Ancient civilization",
  "Androids",
  "Antihero",
  "Apocalyptic",
  "Arranged marriage",
  "Artificial intelligence",
  "Assassins",
  "Awakening",
  "Battle royale",
  "Beast taming",
  "Betrayal of trust",
  "Blackmail",
  "Blood magic",
  "Body swap",
  "Bounty hunters",
  "Brotherhood",
  "Bullying victim",
  "Business",
  "Card games",
  "Childhood friends",
  "Chosen one",
  "Class struggle",
  "Cold war",
  "Coming of age",
  "Competition",
  "Conspiracy",
  "Corporate",
  "Corruption",
  "Court intrigue",
  "Crime",
  "Cultivation",
  "Curses",
  "Cyberpunk",
  "Dark fantasy",
  "Death games",
  "Debt",
  "Deception",
  "Demons",
  "Detective",
  "Discrimination",
  "Disease",
  "Doppelganger",
  "Dragons",
  "Dreams",
  "Dual identity",
  "Dystopia",
  "Economic warfare",
  "Elemental magic",
  "Elves",
  "Empire building",
  "Enemies to lovers",
  "Espionage",
  "Evolution",
  "Exile",
  "Experiments",
  "Exploration",
  "Family business",
  "Family curse",
  "Family secrets",
  "Fantasy creatures",
  "Fate",
  "Father figure",
  "Fear",
  "Feudalism",
  "First love",
  "Forbidden love",
  "Foreign invasion",
  "Friendship betrayal",
  "Gambling",
  "Gang warfare",
  "Genetic engineering",
  "Ghosts",
  "Giants",
  "Gladiators",
  "Government conspiracy",
  "Guilds",
  "Hacking",
  "Haunted",
  "Healing",
  "Hidden identity",
  "Hidden powers",
  "Historical",
  "Honor",
  "Immortality",
  "Imperial court",
  "Inheritance",
  "Injustice",
  "Inner demons",
  "Insanity",
  "Interdimensional",
  "Investigation",
  "Isolation",
  "Jealousy",
  "Justice",
  "Kidnapping",
  "Kingdom building",
  "Knights",
  "Leadership",
  "Lost memories",
  "Love triangle",
  "Loyalty",
  "Mafia",
  "Magic academy",
  "Magic items",
  "Magic school",
  "Magical creatures",
  "Magical girl",
  "Marriage",
  "Martial arts tournament",
  "Master-student",
  "Mechs",
  "Medical",
  "Memory loss",
  "Mental illness",
  "Mercenaries",
  "Military",
  "Mind control",
  "Modern fantasy",
  "Money",
  "Moral ambiguity",
  "Multiple personalities",
  "Murder mystery",
  "Mutants",
  "Mythology",
  "Necromancy",
  "Ninja",
  "Nobility politics",
  "Obsession",
  "Organized crime",
  "Orphans",
  "Parallel worlds",
  "Parasites",
  "Past life",
  "Pirates",
  "Political intrigue",
  "Possession",
  "Post-apocalyptic",
  "Power corruption",
  "Power struggle",
  "Prophecy",
  "Psychic powers",
  "Psychological warfare",
  "Racism",
  "Rebellion",
  "Redemption",
  "Regression",
  "Reincarnated villain",
  "Religion",
  "Resurrection",
  "Robots",
  "Romance",
  "Royal family",
  "Sacrifice",
  "School bullying",
  "School competition",
  "Science experiment",
  "Secret identity",
  "Secret society",
  "Shapeshifters",
  "Siblings",
  "Slavery",
  "Space",
  "Spirits",
  "Sports",
  "Steampunk",
  "Supernatural beings",
  "Superpowers",
  "System",
  "Teamwork",
  "Technology",
  "Teleportation",
  "Terrorism",
  "Time loop",
  "Time manipulation",
  "Torture",
  "Transformation",
  "Transmigration",
  "Treasure hunting",
  "Undercover",
  "Underworld",
  "Unrequited love",
  "Urban fantasy",
  "Vengeance",
  "Video games",
  "Villainess",
  "War",
  "Weak to strong",
  "Werewolves",
  "Witches",
  "Wizards",
  "World building",
  "Zombies",
  "Ancient magic",
  "Artifact hunting",
  "Banishment",
  "Beast companions",
  "Blood pacts",
  "Bodyguards",
  "Bounty hunting",
  "Brainwashing",
  "Celebrity",
  "Childhood trauma",
  "Clone",
  "Contract marriage",
  "Cooking",
  "Corporate espionage",
  "Court politics",
  "Crafting",
  "Criminal underworld",
  "Cross-dressing",
  "Cultural clash",
  "Curse breaking",
  "Dance",
  "Dark magic",
  "Death penalty",
  "Demon king",
  "Dimensional travel",
  "Divine intervention",
  "Double agent",
  "Dragon slaying",
  "Dream world",
  "Drug dealing",
  "Dungeon exploration",
  "Economic collapse",
  "Elemental powers",
  "Elite society",
  "Emotional manipulation",
  "Enchanted objects",
  "Environmental disaster",
  "Eternal life",
  "Evil organization",
  "Exile return",
  "Fake death",
  "False accusation",
  "Family honor",
  "Fantasy politics",
  "Fashion",
  "Female protagonist",
  "Financial crisis",
  "Fire magic",
  "Forbidden knowledge",
  "Foreign culture",
  "Forgotten past",
  "Fortune telling",
  "Found family",
  "Fraud",
  "Freedom fighter",
  "Friendship rivalry",
  "Future sight",
  "Gender bender",
  "Genetic modification",
  "Ghost hunting",
  "God complex",
  "Government corruption",
  "Guild politics",
  "Harem",
  "Healing magic",
  "Hero complex",
  "Hidden agenda",
  "Hidden treasure",
  "High society",
  "Historical figures",
  "Holy war",
  "Human experimentation",
  "Hunter guild",
  "Ice magic",
  "Identity crisis",
  "Illegal fighting",
  "Immortal beings",
  "Imperial succession",
  "Impossible love",
  "Industrial revolution",
  "Information warfare",
  "Inheritance dispute",
  "Inner strength",
  "Interdimensional beings",
  "International conflict",
  "Invisible powers",
  "Island survival",
  "Job hunting",
  "Judicial system",
  "Karma",
  "Kidnapped family",
  "King making",
  "Knowledge seeking",
  "Language barrier",
  "Last survivor",
  "Law enforcement",
  "Legacy",
  "Life debt",
  "Light magic",
  "Living weapon",
  "Lost civilization",
  "Lost kingdom",
  "Love at first sight",
  "Magical artifacts",
  "Magical beasts",
  "Magical contracts",
  "Male protagonist",
  "Marriage politics",
  "Masked identity",
  "Master craftsman",
  "Medical mystery",
  "Memory manipulation",
  "Mental powers",
  "Merchant",
  "Military academy",
  "Mind reading",
  "Misunderstanding",
  "Monster hunting",
  "Moral dilemma",
  "Multiple timelines",
  "Music",
  "Mysterious organization",
  "Mythical beasts",
  "Natural disaster",
  "Naval warfare",
  "Near death experience",
  "Negotiation",
  "Night creatures",
  "Noble sacrifice",
  "Nomadic life",
  "Nuclear war",
  "Oath breaking",
  "Ocean exploration",
  "One-sided love",
  "Online gaming",
  "Organized rebellion",
  "Otherworldly",
  "Outcast",
  "Overprotective",
  "Parallel universe",
  "Parental abandonment",
  "Past sins",
  "Peaceful resolution",
  "Personal growth",
  "Phantom",
  "Philosophical",
  "Physical transformation",
  "Plague",
  "Political marriage",
  "Portal fantasy",
  "Possession by spirit",
  "Post-war",
  "Power awakening",
  "Power imbalance",
  "Precognition",
  "Prehistoric",
  "Prison",
  "Professional rivalry",
  "Protective instinct",
  "Psychic abilities",
  "Public enemy",
  "Quest",
  "Racial conflict",
  "Rare abilities",
  "Reality manipulation",
  "Rebirth",
  "Reconciliation",
  "Refugee",
  "Regret",
  "Reincarnated as monster",
  "Religious conflict",
  "Rescue mission",
  "Resistance movement",
  "Responsibility",
  "Restricted magic",
  "Reverse harem",
  "Righteous anger",
  "Ritual magic",
  "Rival schools",
  "Robot uprising",
  "Role reversal",
  "Romance subplot",
  "Royal guard",
  "Rune magic",
  "Sacred duty",
  "Samurai",
  "School festival",
  "Scientific discovery",
  "Sea adventure",
  "Second chance",
  "Secret base",
  "Secret weapon",
  "Self-discovery",
  "Self-sacrifice",
  "Servant",
  "Shadow magic",
  "Shared consciousness",
  "Sibling rivalry",
  "Skill acquisition",
  "Slave rebellion",
  "Social experiment",
  "Soul magic",
  "Space exploration",
  "Special forces",
  "Spell casting",
  "Spirit world",
  "Spy network",
  "Star-crossed lovers",
  "Status quo",
  "Strategic warfare",
  "Street fighting",
  "Superhero",
  "Supernatural investigation",
  "Survival horror",
  "Sword fighting",
  "Tactical combat",
  "Talent show",
  "Teacher-student",
  "Team building",
  "Technological advancement",
  "Telepathy",
  "Temporal paradox",
  "Territory war",
  "Test of character",
  "Theft",
  "Thought control",
  "Throne succession",
  "Time constraint",
  "Time skip",
  "Tournament arc",
  "Trade war",
  "Training montage",
  "Transformation sequence",
  "Travel",
  "Treasure map",
  "Trial by combat",
  "Tribal conflict",
  "True love",
  "Trust issues",
  "Twin",
  "Underground fighting",
  "Underdog story",
  "Unexpected alliance",
  "Unique ability",
  "Universal threat",
  "Unlikely hero",
  "Unreliable narrator",
  "Uprising",
  "Urban legend",
  "Vacation",
  "Vampire hunter",
  "Vendetta",
  "Video game world",
  "Village life",
  "Villain protagonist",
  "Virtual world",
  "Vision quest",
  "Void magic",
  "War crimes",
  "Water magic",
  "Weapon master",
  "Weather control",
  "Wedding",
  "Wind magic",
  "Wish fulfillment",
  "Witch hunt",
  "World conquest",
  "World ending",
  "World tree",
  "Yakuza",
  "Youth",
  "Zombie apocalypse",
]
